name: GitHub-actions CI build runner

env:
  sfos_target32: ${{ '3.3.0.14' }}

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: mkdir RPMS

    - name: Build armv7hl
      uses: coderus/github-sfos-build@master
      with:
        release: ${{ env.sfos_target32 }}
        arch: armv7hl

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: rpm-build-result
        path: RPMS

    - name: Create release
      if: contains(github.ref, 'release')
      run: |
        set -x
        assets=()
        for asset in RPMS/*.rpm; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
