name: CI on SFOS 3.1.0

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - devel
      - '*legacy*'

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache SDK image
      id: cache-sdk
      uses: actions/cache@v3
      with:
        path: 'coderus/github-sfos-build*'
        key: cache

    - name: Prepare
      run: mkdir RPMS

    - name: Build armv7hl
      uses: coderus/github-sfos-build@old-stable
      with:
        release: 3.1.0.12
        arch: armv7hl

    - name: Debug output
      run: |
        pwd
        sudo find -L /home /imagegeneration /media /mnt /opt /root /run /srv /tmp /var -type f -size 500M -printf "%s  %p\n"

    - name: Upload build result
      uses: actions/upload-artifact@v3
      with:
        name: rpm-build-result
        path: RPMS/

